sudo: false
language: node_js
matrix:
  include:
    - node_js: node # Current
      env: BUILD_DOCS=true REPORT_COVERAGE=true
    - node_js: lts/* # Latest LTS
      env: NPM_DEPLOY=true
    - node_js: lts/carbon
    - node_js: lts/boron
    - node_js: 4 # Minimum required
      before_script: 'echo "Warning: skipping linting on NodeJS 4" >&2'
      script: 'echo "Warning: disabled code coverage on NodeJS 4" >&2 && npm run mocha'
before_script:
  - npm run lint
script:
  - npm test -- -- --timeout 10000
  - '[[ "$BUILD_DOCS" != true ]] || npm run doc' # Ensures ESDoc generation doesn't fail
after_success:
  - '[[ "$REPORT_COVERAGE" != true ]] || cat coverage/lcov.info | ./node_modules/.bin/codecov'
deploy:
  provider: npm
  email: pro.alexandre.mercier@gmail.com
  api_key: $NPM_AUTH_TOKEN
  on:
    tags: true
    repo: amercier/es6-mixin # Prevents publishing on PRs
    condition: $NPM_DEPLOY = true # Prevents publishing on each matrix build
cache:
  directories:
  - $HOME/.nvm
